# -*- coding: utf-8 -*-
"""examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17eP2B9UuxQKmSsnfG81pKcZ8erLYRksz
"""

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

a = 5
print(factorial(a))
print(a / b)

person = {'name': 'Alice', 'age': 30}
print(person[0]) # Bug: Accessing the dictionary with an integer index instead of a string key.

my_number = 10
my_number.append(5) # Bug: 'append' is a list method, not an integer method.

i = 0
while i < 5:
    print(i) # Bug: The loop variable 'i' is never incremented, so the condition is always true.